# inspired by rhinstaller/anaconda

name: Trigger GitLab CI

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  trigger-gitlab:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      SCHUTZBOT_SSH_KEY: I_DONT_CARE
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Download
        uses: actions/github-script@v5
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "my-artifacts"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/my-artifacts.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip my-artifacts.zip
      - name: SKIP_CI?
        run: |
          set -x
          echo "${SECRET}"
          SKIP_CI=$(cat SKIP_CI.txt)
          [[ "${SKIP_CI}" == true ]] && PUSH_OPTION='-o ci.variable="SKIP_CI=true"' || PUSH_OPTION=""
          if [[ "${SKIP_CI}" == true ]];then
            echo "DO SKIP CI"
          else
            echo "DO NOT SKIP CI"
          fi
